service: send-mail
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256

functions:
  sendMail:
    handler: sendMail.handle
    events:
      - http: POST /